service: tour
runtime: go
api_version: go1

default_expiration: "7d"

handlers:

# Keep these static file handlers in sync with local.go.
- url: /favicon.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon.ico
  secure: always
- url: /content/img
  static_dir: content/img
  secure: always
- url: /static
  static_dir: static
  application_readable: true
  secure: always

- url: /(.*|list|lesson/.*|compile|fmt|script\.js)
  script: _go_app
  secure: always

nobuild_files: (solutions|content)/.*
