service: tour
runtime: go114

env_variables:
  GOLANGORG_CHECK_COUNTRY: true
  TOUR_ANALYTICS: |
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-11222381-5"></script>
    <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag("js", new Date());
    gtag("config", "UA-11222381-5");
    gtag("config", "UA-49880327-6");
    </script>

default_expiration: "7d"

handlers:

# Keep these static file handlers in sync with local.go.
# They're here for improved latency across global regions.
- url: /favicon.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon.ico
  secure: always
- url: /content/img
  static_dir: content/img
  secure: always
- url: /static
  static_dir: static
  secure: always

# This is here to redirect all HTTP traffic to an HTTPS URL
# with the same path.
- url: /.*
  script: auto
  secure: always
